### ISSUE TITLE
Example App Google Pay Button Crash

### ISSUE THREAD

**Issue by adxzhang1** [flutter-stripe/flutter_stripe#101]
**Describe the bug**
The example app crashes when closing the google pay dialog after opening it from the google pay button.

Error:
Failure delivering result ResultInfo{who=null, request=991, result=0, data=Intent { (has extras) }} to activity {com.flutter.stripe.example/com.flutter.stripe.example.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property stripe has not been initialized

**To Reproduce**
1. Launch the example app.
2. Open google pay screen.
3. Tap google pay button.
4. Close google pay dialog that comes up.

**Smartphone / tablet**
 - Android Simulator API 30
 - Android Device Android 10

**Comment by jonasbark** [comment]
Did you follow the requirements? https://github.com/flutter-stripe/flutter_stripe#android
Namely the theme and Activity change

**Comment by adxzhang1** [comment]
Thanks for the quick reply! Yes, I cloned and am using the example app and it has those changes. 
I am also testing a demo app and may have found the error and will update back shortly.

**Comment by adxzhang1** [comment]
Hi I just made a repo demoing the error [https://github.com/adxzhang1/flutter_stripe_issue](here). It seems that after adding the FlutterFragmentActivity the issue pops up. This is also getting the same error:
Failure delivering result ResultInfo{who=null, request=991, result=0, data=Intent { (has extras) }} to activity {com.example.payment_demo/com.example.payment_demo.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property stripe has not been initialized

**Comment by jonasbark** [comment]
Just a guess: you should also update https://github.com/adxzhang1/flutter_stripe_issue/blob/error/android/app/src/main/res/values-night/styles.xml#L15 when you use dark mode

**Comment by adxzhang1** [comment]
I just tried it using the same parent as the light one and still get the issue.

**Comment by TomMichalkevic** [comment]
I am having the exact same issue. Even though Stripe is indeed initialized in main method.

**Comment by jonasbark** [comment]
Thanks for reporting - this ticket is a duplicate of https://github.com/flutter-stripe/flutter_stripe/issues/68 and already fixed in the main branch. We'll release a new version soon.

So long you could use:
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_stripe:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: packages/stripe
  pay: ^1.0.1

dependency_overrides:
  stripe_android:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: packages/stripe_android
```
