### ISSUE TITLE
Gradle failed with error Could not determine the dependencies of task ':stripe_android:compileReleaseAidl'

### ISSUE THREAD

**Issue by yossefEl** [flutter-stripe/flutter_stripe#1091]
**Describe the bug**
Using flutter_stripe^5.2.1, the app was working without errors a month ago
4 Days ago I was trying to make some updates and I get this error directly after running the command<br> `flutter run` or `flutter build apk`
I tried all possible solutions 
- Upgrading and downgrading flutter  (2.10.x, 3.0.0 , 3.0.1 ,3.3.0 and 3.3.9) 
- Upgrading and downgrading the JDK version (17,12 and 11)
- Upgrading and downgrading the flutter_stripe version (5.2.1, 6.0.0 and 7.0.0)
- Changing the Gradle version 
- Changing the build tools version 
- etc :)

```
Warning: Premature end of file.
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1013)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)

        ............

        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':stripe_android:compileReleaseAidl'.
> javax.xml.bind.UnmarshalException (no error message)
```
**flutter doctor**
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6.1 21G217 darwin-x64, locale en-XX)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```
**JDK version and Gradle**
```
Gradle 7.4
Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:      3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          12.0.2 (Oracle Corporation 12.0.2+10)
OS:           Mac OS X 10.16 x86_64
```

**Comment by remonh87** [comment]
you use an outdated version of kotlin. Please change the kotlin version to:

ext.kotlin_version = '1.7.10'

**Comment by yossefEl** [comment]
Hi @remonh87 , thank you for your support. 
I'm already using the version you mentioned 1.7.10. I also changed to Gradle @7.6 which uses this version of Kotlin but I'm still getting the same error.

**Comment by remonh87** [comment]
btw it looks like some xml in the app is malformed. Are you using some document scanner library?

**Comment by yossefEl** [comment]
No, I'm not using it, I also tried with the example app of that package but I get the same issue 😞  .
these are the dependencies I'm using :
```
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  url_launcher: ^6.0.20
  carousel_slider: ^4.0.0
  provider: ^6.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  get: ^4.6.5
  flutter_screenutil: ^5.5.2
  cached_network_image: ^3.2.1
  responsive_builder: ^0.4.2
  auto_animated: ^3.0.1
  shimmer: ^2.0.0
  pull_to_refresh_flutter3: ^2.0.1
  email_validator: ^2.0.1
  in_app_review: ^2.0.4
  fluttertoast: ^8.0.9
  share_plus: ^6.3.0
  dotted_border: ^2.0.0+2
  fluentui_system_icons: ^1.1.172
  flutter_stripe: ^7.0.0
  local_auth: ^2.1.2
  flutter_inappwebview: ^5.7.2+3
  story:
    git:
      url: https://github.com/yossefEl/story.git
      ref: main
  strapi_sdk_flutter:
    path: /Users/josephel/Documents/flutter_packages/strapi-sdk-flutter
  firebase: ^9.0.3
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  firebase_dynamic_links: ^5.0.11
  firebase_crashlytics: ^3.0.9
  flutter_native_splash: ^2.2.10+1
  jwt_decoder: ^2.0.1
```
