### ISSUE TITLE
Unhandled payment Element loaderror. on PaymentElement widget [web]

### ISSUE THREAD

**Issue by par400** [flutter-stripe/flutter_stripe#1129]
I'm trying to use [PaymentElement](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_web/lib/src/widgets/payment_element.dart) widget for web app but when I add try to use the widget in my app. 
I get error `Unhandled payment Element loaderror`

actual payment element stripe doc: https://stripe.com/docs/payments/payment-element

I initialize webstripe and stripe
```
await WebStripe().initialise(
        publishableKey: Environment().config.stripeKey,
        stripeAccountId: session.stripeId,
        merchantIdentifier: 'merchant.com.xxx');

    Stripe.publishableKey = Environment().config.stripeKey;
    Stripe.stripeAccountId = session.stripeId;
    Stripe.merchantIdentifier = 'merchant.com.xxx';
    await Stripe.instance.applySettings();
```
Then I add the `PaymentElement` widget within one of my screen's Scaffold body:
```
...
PaymentElement(
                  autofocus: true,
                  enablePostalCode: false,
                  onFocus: (focusedField) {
                    Logger().d('current ofcused: ${focusedField?.index}');
                  },
                  onCardChanged: (onCardChanged) {
                    Logger().d('oncardchangeed ${onCardChanged?.toString()}');
                    Logger().d('oncardchangeed ${onCardChanged?.last4}');
                  },
                  clientSecret: widget.clientSecret),
...
```

**Smartphone / tablet**
 - Device: chrome
 - OS: Venture 13.2
 - Package version: flutter_stripe: ^8.0.0+1, flutter_stripe_web: ^3.0.0
 - Flutter version 3.7

Any idea what could be the issue?

**Comment by jamesblasco** [comment]
Hi @par400 , sorry I did not get to see this issue before. Could you try to update to the latest versions of the package to see if it works for you? Otherwise could you provide a bit more detail on what is the error?

**Comment by smp27768** [comment]
@jamesblasco I'm also getting this issue when building for Flutter Web. The error in question prevents `PaymentElement` from rendering as intended (it'll show up for a brief second, then disappear).

• Stripe package versions, as defined in my `pubspec.lock` file:
```
flutter_stripe:
    dependency: "direct main"
    description:
      name: flutter_stripe
      sha256: fb1a0647867a26b1fced98706ef96c664a5ae2579e29b67af5ddd054e01d83df
      url: "https://pub.dev"
    source: hosted
    version: "9.2.2"
flutter_stripe_web:
    dependency: "direct main"
    description:
      name: flutter_stripe_web
      sha256: e6ffc95641914706d5967922053be7c14647ed2b3f751cc0b2056654950c7a5b
      url: "https://pub.dev"
    source: hosted
    version: "4.2.0"
```
-----------
• Source code & console output:
```
import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:flutter_stripe_web/flutter_stripe_web.dart';

class PlatformPaymentElement extends StatelessWidget {
  const PlatformPaymentElement(
    this.clientSecret,
    this.onCardChanged, {
    super.key,
  });

  final String? clientSecret;
  final Function(CardFieldInputDetails?) onCardChanged;

  @override
  Widget build(BuildContext context) {
    debugPrint('BUILD PAYMENTELEMENT WIDGET');
    debugPrint('=> Non-empty client secret: ${clientSecret ?? ''}');
    debugPrint('=> Stripe key: ${Stripe.publishableKey}');
    return PaymentElement(
      autofocus: true,
      enablePostalCode: false,
      onCardChanged: onCardChanged,
      clientSecret: clientSecret ?? '',
    );
  }
}
```

<img width="917" alt="Screenshot 2023-07-01 at 2 33 33 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/32310695/33c50656-e2d7-45ad-9c9c-ba803a96178b">

-----------
• Web output:

https://github.com/flutter-stripe/flutter_stripe/assets/32310695/3df2c23f-da10-4a96-90b4-1bcf019c3a06
