### ISSUE TITLE
@yosuke-nakayama  Android gradle plugin 8 is required for people who want to compile on sdk 34 see: https://developer.android.com/build/releases/gradle-plugin#api-level-support . The fact that others do not update their  plugins is not something we can cater for. For example app_review is not updated in 16 months

### ISSUE THREAD

**Issue by elmar001** [flutter-stripe/flutter_stripe#1580]
@yosuke-nakayama  Android gradle plugin 8 is required for people who want to compile on sdk 34 see: https://developer.android.com/build/releases/gradle-plugin#api-level-support . The fact that others do not update their  plugins is not something we can cater for. For example app_review is not updated in 16 months

That said  people can still use version 9.5.0 use dependency overrides to fix the versions for this like: 

```yaml
dependency_overrides:
  flutter_stripe: "9.5..1"
  stripe_android: "9.5.1"
  stripe_ios: "9.5.1"
  stripe_platform_interface:  "9.5.1"
```

_Originally posted by @remonh87 in https://github.com/flutter-stripe/flutter_stripe/issues/1513#issuecomment-1833221851_
