### ISSUE TITLE
Android App crashes in Release mode with com.android.application version >= 8

### ISSUE THREAD

**Issue by lokus1980** [flutter-stripe/flutter_stripe#1909]
Hello,

As the title suggests, this Stripe library does not work on any of my Android phones (for example, the Pixel 6 with Android 14).

Detailed log from the crash in Release build: [crash.log](https://github.com/user-attachments/files/16842104/crash.log)

I have tested on multiple phones with Android 10 and Android 14. It always works in Debug mode but crashes instantly in Release mode. Please help.

```
Flutter: 3.24.1 (latest version)
flutter_stripe: 11.0.0 (latest version)
```

Also, I have done every single installation step as described here:
https://pub.dev/packages/flutter_stripe

That's the piece of code that shows the payment sheet:
<img width="310" alt="payment sheet" src="https://github.com/user-attachments/assets/b12b746d-b3f0-4409-8e20-b416b883a382">

Video from Debug build (works):
https://github.com/user-attachments/assets/ef3eba99-6180-4f5a-8a09-0933f76e5641

Video from Release build (crashes):
https://github.com/user-attachments/assets/bc5daedd-4ef3-4fcf-9116-17815776cddc

This blocks me from releasing the app to production as the payment feature is the core functionality here. The only thing I need for my MVP is to allow customers to pay by card. Nothing else is required at this stage and even this scenario does not work. And I don't want to publish a Debug version to production...

Please help. I have invested lots of time integrating Stripe with my backend but it's not usable end to end as the mobile app (currently my only API client) is not working at all. Thank you.

**Comment by remonh87** [comment]
so deadobject exception means the paymentsheetactivity got killed by the android OS. Can it be that you do not have applied all the steps for android as described [here](https://github.com/flutter-stripe/flutter_stripe?tab=readme-ov-file#android)?  

I am using paymentsheet as well and do not have this issue

**Comment by lokus1980** [comment]
Yes @remonh87, I have done all the steps like in the instruction and getting:

```
09-04 06:18:58.892   511  1826 W WindowManager: Exception thrown during dispatchAppVisibility Window{81048b0 u0 com.gameos.goxp.dev/com.gameos.goxp.dev.MainActivity EXITING}
09-04 06:18:58.892   511  1826 W WindowManager: android.os.DeadObjectException
09-04 06:18:58.892   511  1826 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
09-04 06:18:58.892   511  1826 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
09-04 06:18:58.892   511  1826 W WindowManager: 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:546)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3271)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1221)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:409)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6946)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5637)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5580)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.Transition.finishTransition(Transition.java:1151)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:868)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:396)
09-04 06:18:58.892   511  1826 W WindowManager: 	at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:286)
09-04 06:18:58.892   511  1826 W WindowManager: 	at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:181)
09-04 06:18:58.892   511  1826 W WindowManager: 	at android.os.Binder.execTransactInternal(Binder.java:1339)
09-04 06:18:58.892   511  1826 W WindowManager: 	at android.os.Binder.execTransact(Binder.java:1275)
09-04 06:18:58.892   511  1826 I Process : Sending signal. PID: 5886 SIG: 9
09-04 06:18:58.896   511   531 W ActivityManager: setHasOverlayUi called on unknown pid: 5886
09-04 06:18:58.901   719   820 V WindowManagerShell: Track 0 became idle
09-04 06:18:58.901   719   820 V WindowManagerShell: All active transition animations finished
09-04 06:18:58.920   374   374 E BpTransactionCompletedListener: Failed to transact (-32)
09-04 06:18:58.920   374   374 E BpTransactionCompletedListener: Failed to transact (-32)
09-04 06:18:59.797   511   590 D ActivityManager: freezing 1187 com.google.android.permissioncontroller
```

Now, please look at my configuration and see if you can spot anything:
```
Flutter: 3.24.0 (latest version)
flutter_stripe: 11.0.0 (latest version)
```

Pubspec.yaml:
```
name: goxp
description: GoXP app
publish_to: 'none'
version: 0.2.0+154

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  equatable: ^2.0.5
  mocktail: ^1.0.3
  badges: ^3.1.1
  collection: ^1.18.0
  uuid: ^4.3.3
  flutter_native_splash: ^2.3.1
  amplify_auth_cognito: ^2.3.0
  amplify_authenticator: ^2.1.1
  flutter_rating_bar: ^4.0.1
  amplify_api: ^2.3.0
  form_builder_validators: ^11.0.0
  image_picker: ^1.0.4
  http: ^1.1.0
  go_router: ^14.2.0
  flutter_stripe: ^10.2.0
  url_launcher: ^6.3.0
  amplify_flutter: ^2.3.0
  http_parser: ^4.0.2
  settings_ui: ^2.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/initialisation/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 800
          style: italic

flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"

flutter_native_splash:
  color: "#0D0160"
  color_dark: "#0D0160"
  image_ios: assets/images/splash/splash.png
  ios_content_mode: scaleAspectFill
  android_12:
    image: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  image_android: assets/images/splash/splash.png
  android_gravity: center
```

main.dart:
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  Stripe.publishableKey =
      "pk_test_*********";
  Stripe.merchantIdentifier = 'merchant.flutter.stripe.test';
  Stripe.urlScheme = 'goxpdev';
  await Stripe.instance.applySettings();
  ...
```

styles.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is off -->
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```

styles.xml (at values-night):
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is on -->
    <!-- TODO document the necessary change -->
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```

android/build.gradle:
```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

android/app/build.gradle:
```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id "com.google.gms.google-services"
    id "com.google.firebase.crashlytics"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.gameos.goxp.dev"
    compileSdk 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.gameos.goxp.dev"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 24
        targetSdkVersion 33
        // targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.google.firebase:firebase-iid:21.1.0'
    implementation 'com.google.android.gms:play-services-base:18.1.0'
}
```

proguard-rules.pro:
```
 -dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivity$g
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider
```

gradle-wraper.properties:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

MainActivity.kt:
```
package com.gameos.goxp.dev

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}
```

and the code that is presenting the payment sheet:
```
  Future<void> _bookCurrentExperience(Store<AppState> store, BookCurrentExperience action, NextDispatcher next) async {
    store.dispatch(const ShowLoader());
    try {
      final experienceId = store.state.experienceState.currentExperience!.id;
      final priceOptionId = action.priceOptionId;
      final experienceModifiedAt = store.state.experienceState.currentExperience!.modifiedAt;
      // 1. create payment intent on the server
      final paymentIntent = await _createPaymentIntent(experienceId, priceOptionId, experienceModifiedAt);
      // 2. set publishable key
      // Stripe.publishableKey = paymentIntent.publishableKey;
      // 3. initialize the payment sheet
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          customFlow: false,
          merchantDisplayName: 'GoXP',
          paymentIntentClientSecret: paymentIntent.clientSecret,
          customerEphemeralKeySecret: paymentIntent.ephemeralKey,
          customerId: paymentIntent.stripeCustomerId,
        ),
      );
      // 4. present payment sheet
      await Stripe.instance.presentPaymentSheet();
      safePrint("Payment completed!!!");
      // TODO: navigate to "Thank for booking your experience. Check your inbox for a confirmation email"
      next(action);
    } catch (e) {
      // TODO: show a popup with an error message
      safePrint(e);
    } finally {
      store.dispatch(const HideLoader());
    }
  }
```

I am running out of ideas. I tried lots of things like fiddling with `customFlow`, `targetSdkVersion`, `flutter-stripe` version and still getting the `android.os.DeadObjectException`.
