### ISSUE TITLE
Not Getting Card's Fingerprint in Flutter... plugin :- flutter_stripe: ^2.5.0

### ISSUE THREAD

**Issue by jaimik11** [flutter-stripe/flutter_stripe#707]
/// Card data associated with the payment method
class Card with _$Card {
  @JsonSerializable(explicitToJson: true)
  const factory Card({
    /// The brand associated to the card e.g. (visa, amex).
    String? brand,

    /// Two letter iso code.
    String? country,

    /// four digit number representing the year of expiry of the card.
    int? expYear,

    /// two digit number representing the month of expire of the card.
    int? expMonth,

    /// card funding type e.g. (credit, debit).
    String? funding,

    /// last four digits of the card.
    String? last4,
  }) = _Card;

  factory Card.fromJson(Map<String, dynamic> json) => _$CardFromJson(json);
}

Not Getting Card Fingerprint, How can I validate if card already exists or attached to customer? Because as of now, the customer can add many Cards with the same details. I've read in some SDKs / Library that we can check it using the payment_method's fingerprint but I'm not able to see it when I access the Card properties. How can i check card is unique or not ?

**Comment by jonasbark** [comment]
This will be available soon https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md

**Comment by Flucadetena** [comment]
Was this ever add it? How can we access it in either android or IOS?

Thanks for the time and help.

**Comment by Flucadetena** [comment]
Hi @jaimik11 not sure you still need this but I created a pull request to fix this issue. Hopefully it will get merged soon ;)
In the meantime you can use my fork like this. Hope it helps ;)

In your pubspec.yaml
```
  flutter_stripe:
    git:
      url: https://github.com/Flucadetena/flutter_stripe.git
      path: packages/stripe

dependency_overrides:
  stripe_platform_interface:
    git:
      url: https://github.com/Flucadetena/flutter_stripe.git
      path: packages/stripe_platform_interface
```
